version: '3.7'

services:
  app:
    build:
      context: node
    networks:
      - fullcycle-network
    volumes:
      - ./node:/usr/src/app
      - nodemodules:/usr/src/app/node_modules
    tty: true
    container_name: appfullcycle
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s npm start
    depends_on:
      - db
  db:
    build:
      context: ./mysql
    container_name: dbfullcycle
    restart: always
    tty: true
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=dbfullcycle
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcycle-network
  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - fullcycle-network
    ports:
      - "8080:80"
    depends_on:
      - app
  
networks:
  fullcycle-network:
    driver: bridge
volumes:
  nodemodules: {}
